config/routes.rb
ScaffoldTest::Application.routes.draw do
  resources :shops
  resources :users
  resources :links
  match 'serch', :to => 'users#search'
  match '/serch', :to => 'users#serch'
  match ':controller(/:action(/:id(.:format)))'
  
  
  match ':controller(/:action(/:id(.:format)))'

end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :traffic
  #key
  has_many :shop
  has_many :user
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  attr_accessible :link_id, :name, :offer
  #key
  belongs_to:link
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :comment, :link_id, :name
  #key
  belongs_to:link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  
  
  # GET /links
  # GET /links.json
  def index
    @links = Link.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @links }
    end
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @link = Link.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/new
  # GET /links/new.json
  def new
    @link = Link.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/1/edit
  def edit
    @link = Link.find(params[:id])
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(params[:link])

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render json: @link, status: :created, location: @link }
      else
        format.html { render action: "new" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /links/1
  # PUT /links/1.json
  def update
    @link = Link.find(params[:id])

    respond_to do |format|
      if @link.update_attributes(params[:link])
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link = Link.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shops }
    end
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
    @shop = Shop.find(params[:id])

    respond_to do |format|
      format.html { render layout: (request.headers["X-Requested-With"] != 'XMLHttpRequest') }
      format.json { render json: @shop }
    end
  end

  # GET /shops/new
  # GET /shops/new.json
  def new
    @shop = Shop.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shop }
    end
  end

  # GET /shops/1/edit
  def edit
    @shop = Shop.find(params[:id])
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(params[:shop])

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render json: @shop, status: :created, location: @shop }
      else
        format.html { render action: "new" }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shops/1
  # PUT /shops/1.json
  def update
    @shop = Shop.find(params[:id])

    respond_to do |format|
      if @shop.update_attributes(params[:shop])
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy

    respond_to do |format|
      format.html { redirect_to shops_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  respond_to :html, :json
  
  def index
    @users = User.all
    respond_with @users
  end

  def show
    @user = User.find(params[:id])
    respond_with @user
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    @user.save
    respond_with @user
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    respond_with @user
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_with @user
  end
  
  def serch
  end
  
  def showone
  	@user = User.find(params[:num])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    
  </small>
  <nav>
    <ul>
      
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
    
      <%= link_to "Top", serch_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          
          
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Books</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
 <%= render 'layouts/header' %>
 <div class="container">
   <%= yield %>
   <%= render 'layouts/footer' %>
 </div>
</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :traffic %><br />
    <%= f.number_field :traffic %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<h1>Map View</h1>


<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<%= link_to image_tag("130905_Link.png", alt: "Rails") %>
			<br><br><br><br>
		</div>
	</div>
</div>

<div class="container-fluid">
	<div class="row-fluid">
		<div class="span6">
			<table class="table table-striped table-bordered table-condensed">
				<thead>
					<tr>
						<th>
							Link_id
						</th>
						<th>
							Name
						</th>
						<th>
							Comment
						</th>
						<th>
							Function
						</th>
					</tr>
				</thead>
				<tbody>
					<% @links.each do |link| %>
    					<% link.user.each do |obj| %>
    						<tr>
    							<td><%= link.id %></td>
        						<td><b><%= obj.name %></b></td>
        						<td><%= obj.comment %></td>
        						<td><%= link_to 'Show', link %></td>
    							<td><%= link_to 'Edit', edit_user_path(link) %></td>
    							<td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        					</tr>
    					<% end %>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>



<br />

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>ID:</b>
  <%= @link.id %>
</p>

<p>
  <b>Traffic:</b>
  <%= @link.traffic %>
</p>

<p>
	<b>Comment:</b>
</p>
<p>
  	<% @link.user.each do |obj| %>
  		<% if obj.comment != "" %>
        	<b><%= obj.name %></b><br>
        	<%= obj.comment %><hr/>
    	<% end %>
    <% end %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/shops/_form.html.erb
<%= form_for(@shop, :remote=>true) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
 
 <div class="field">
    <%= f.label :link_id %><br />
    <%= f.number_field :link_id %>
  </div>
 
  <div class="field">
    <%= f.label :offer %><br />
    <%= f.text_field :offer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Editing shop</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<%= javascript_include_tag :defaults %>


<h2>Maps</h2>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<%= link_to image_tag("130905_Link.png", alt: "Rails") %>
			<br><br><br><br>
		</div>
	</div>
</div>




<h2>Shops</h2>

<table class="table table-striped table-bordered table-condensed">
  <tr>
    <th>Name</th>
    <th>Function</th>
    
  </tr>

<% @shops.each do |shop| %>
  <tr>
    <td><%= shop.name %></td>
    <td><%= link_to 'Show', shop, :remote => true, "data-type" => "html", :class => 'show' %></td>
    <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
    <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= link_to 'New Shop', new_shop_path %>
<br />

<div id="show_area"></div>
<%= javascript_tag do %>
$('a.show').on('ajax:success', function (data, status, xhr) {
  $('#show_area').html(status);
})
<% end %>

app/views/shops/new.html.erb
<h1>New shop</h1>

<%= render 'form' %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @shop.name %>
</p>

<p>
  <b>Link:</b>
  <%= @shop.link_id %>
</p>

<p>
  <b>Offer:</b>
  <%= @shop.offer %>
</p>


<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>

app/views/shops/show.js.erb
$('#show_area').html("<%= raw(j(render :partial => 'show_body')) %>")

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :link_id %><br />
    <%= f.number_field :link_id %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="center">

<h1>Welcome</h1>

<h2>New User</h2>
<fieldset>
<button class="btn btn-large btn-primary" type="button"><%= link_to 'New User', new_user_path  %></button>
</fieldset>

</div>

<br />

<h2>View</h2>

<div class="container-fluid" "center hero-unit">
	<div class="row-fluid">
		<div class="span6">
			<table class="table table-striped table-bordered table-condensed" >
				<thead>
					<tr>
						<th>
							User_ID
						</th>
						<th>
							Name
						</th>
						<th>
							Link_ID
						</th>
						<th>
							Comment
						</th>
						<th>
							Function
						</th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |user| %>
  						<tr>
  							<td><%= user.id %></td>
    						<td><%= user.name %></td>
    						<td><%= user.link_id %></td>
    						<td><%= user.comment %></td>
    						<td><%= link_to 'Show', user %></td>
    						<td><%= link_to 'Edit', edit_user_path(user) %></td>
    						<td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/search.html.erb
<div class="center hero-unit">
  <h1>Welcome</h1>

<h2>New User</h2>

<button class="btn btn-large btn-primary" type="button"><%= link_to 'New User', new_user_path  %></button>

<br />

<h2>Search</h2>
<p>Enter User ID</p>
  
<form method="post" action="/users/showone">
 <p>
 <input type="text" name="num" /><br />
 <input type="submit" value="Submit" />
 </p>
</form>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span6">
			<b>User Data:</b>
			<table class="table table-striped table-bordered table-condensed">
				<thead>
					<tr>
						<th>
							User_ID
						</th>
						<th>
							Name
						</th>
						<th>
							Link_ID
						</th>
						<th>
							Comment
						</th>
					</tr>
				</thead>
				<tbody>
  					<tr>
  						<td><%= @user.id %></td>
    					<td><%= @user.name %></td>
    					<td><%= @user.link_id %></td>
    					<td><%= @user.comment %></td>
  					</tr>
				</tbody>
			</table>
			
			<% if @user.comment != "" %>
				<b>Offers:</b>
				<% if @user.link.shop.count != 0 %>
				<% @user.link.shop.each do |obj| %>
				<table class="table table-striped table-bordered table-condensed">
  					
        				<td><b><%= obj.name %></b></td>
        				<td><%= obj.offer %></td>
    				
    			<% end %>
    			<% end %>
    			</table>
  			<% end %>
		</div>
	</div>
</div>





<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', serch_path %>

app/views/users/showone.html.erb
<p>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span6">
			<table class="table table-striped table-bordered table-condensed">
				<thead>
					<tr>
						<th>
							User_ID
						</th>
						<th>
							Name
						</th>
						<th>
							Link_ID
						</th>
						<th>
							Comment
						</th>
					</tr>
				</thead>
				<tbody>
  					<tr>
  						<td><%= @user.id %></td>
    					<td><%= @user.name %></td>
    					<td><%= @user.link_id %></td>
    					<td><%= @user.comment %></td>
  					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>
<%= link_to 'Edit', edit_user_path(@user) %>
</p>